
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft, CreditCard, Loader2 } from "lucide-react";
import Script from "next/script";

export default function Checkout() {
  const [loading, setLoading] = useState(false);
    const [amount, setAmount] = useState(10);
      const router = useRouter();
        const { amount: queryAmount } = router.query;

          // This will run when the component mounts and when the router is ready
            useEffect(() => {
                if (router.isReady) {
                      const parsedAmount = parseFloat(queryAmount);
                            if (!isNaN(parsedAmount) && parsedAmount > 0) {
                                    setAmount(parsedAmount);
                                          }
                                              }
                                                }, [router.isReady, queryAmount]);

                                                  const createOrder = async (e) => {
                                                      e.preventDefault();
                                                          setLoading(true);
                                                              try {
                                                                    const res = await fetch("/api/createCashfreeOrder", {
                                                                            method: "POST",
                                                                                    headers: { "Content-Type": "application/json" },
                                                                                            body: JSON.stringify({
                                                                                                      order_amount: parseFloat(amount),
                                                                                                                // These details would typically come from the logged-in user's state
                                                                                                                          customer_id: "cust_001", 
                                                                                                                                    customer_email: "test@example.com",
                                                                                                                                              customer_phone: "9999999999",
                                                                                                                                                        order_note: `Add to wallet: ${amount}`
                                                                                                                                                                }),
                                                                                                                                                                      });

                                                                                                                                                                            const data = await res.json();

                                                                                                                                                                                  if (data?.payment_session_id) {
                                                                                                                                                                                          const cashfree = new window.Cashfree({ mode: "sandbox" });
                                                                                                                                                                                                  cashfree.checkout({
                                                                                                                                                                                                            paymentSessionId: data.payment_session_id,
                                                                                                                                                                                                                      redirectTarget: "_self",
                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                            alert("Order creation failed: " + (data.message || "Unknown error"));
                                                                                                                                                                                                                                                    console.error(data);
                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                              } catch (err) {
                                                                                                                                                                                                                                                                    alert("Error creating order");
                                                                                                                                                                                                                                                                          console.error(err);
                                                                                                                                                                                                                                                                              } finally {
                                                                                                                                                                                                                                                                                    setLoading(false);
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                <>
                                                                                                                                                                                                                                                                                                      <div className="flex flex-col items-center justify-center min-h-screen bg-background p-4">
                                                                                                                                                                                                                                                                                                              <Card className="w-full max-w-md">
                                                                                                                                                                                                                                                                                                                        <CardHeader>
                                                                                                                                                                                                                                                                                                                                    <Button variant="ghost" size="sm" className="w-fit mb-2 -ml-2" onClick={() => router.back()}>
                                                                                                                                                                                                                                                                                                                                                    <ArrowLeft className="mr-2 h-4 w-4"/> Go Back
                                                                                                                                                                                                                                                                                                                                                                </Button>
                                                                                                                                                                                                                                                                                                                                                                            <CardTitle className="flex items-center gap-2 text-2xl font-headline">
                                                                                                                                                                                                                                                                                                                                                                                          <CreditCard className="h-7 w-7 text-primary" />
                                                                                                                                                                                                                                                                                                                                                                                                        Add Funds to Wallet
                                                                                                                                                                                                                                                                                                                                                                                                                    </CardTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                <CardDescription>Enter the amount you wish to add to your balance.</CardDescription>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <form onSubmit={createOrder} className="space-y-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Label htmlFor="amount" className="block text-sm font-medium">Amount (INR)</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-1 relative rounded-md shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-muted-foreground sm:text-sm">₹</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name="amount"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id="amount"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="pl-7 pr-4 py-2 h-11 text-base"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="10.00"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={amount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setAmount(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            min="1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        step="any"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={!!queryAmount} // Disable if amount is passed in URL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {queryAmount && <p className="mt-2 text-xs text-muted-foreground">This amount is required to complete your previous action.</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        disabled={loading || !amount || amount < 1}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-full h-11 text-base"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                variant="default"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Loader2 className="animate-spin" /> Processing...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            `Pay ₹${amount || 0}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Script src="https://sdk.cashfree.com/js/v3/cashfree.js" strategy="lazyOnload" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
